function openNav() {
    document.getElementById("mySidenav").style.width = "250px";
    document.getElementById("main").style.marginLeft = "250px";
  }

  function closeNav() {
    document.getElementById("mySidenav").style.width = "0";
    document.getElementById("main").style.marginLeft = "0";
  }

function continuar() {
  // função que leva para a proxima página
  window.location.href = "http://127.0.0.1:5501/Estrutura/indentifica%C3%A7%C3%A3o.html"
}